ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = ${PORT}
BOARD_TAG = uno 
AVRDUDE_CONF = $(AVR_TOOLS_DIR)/../avrdude.conf
USER_LIB_PATH = ./libraries
ARDUINO_LIBS = Wire SPI Adafruit_BusIO Adafruit_MAX31865

include /usr/share/arduino/Arduino.mk
